### PR TITLE
Osborne mine airborne magnetic data

### PR DESCRIPTION
**Pull request by leouieda**
This is a section of a survey acquired in 1990 by the Queensland Government,
Australia. The data are good quality with approximately 80 m terrain clearance
and 200 m line spacing. The anomalies are very visible and present interesting
processing and modelling challenges, as well as plenty of literature about
their geology.

* Original source: [Geophysical Acquisition & Processing Section 2019. MIM Data from Mt Isa Inlier, QLD (P1029), magnetic line data, AWAGS levelled. Geoscience Australia, Canberra](http://pid.geoscience.gov.au/dataset/ga/142419)
* Original license: CC-BY

preview

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
I had to do some digging about the `altitude` variable in the dataset. It's clearly not the observation height since topography itself is around 200 m high and the `altitude` hovers around 80 m. That's the nominal terrain clearance so I'm assuming that this is what `altitude` is. To get proper (orthometric) height, I downloaded a 1 arc-second SRTM grid using PyGMT and interpolated it on the data points. I kept the terrain clearance and topography in separate variables in the `DataFrame` which can be a bit of a teachable moment in the docs. 

The rest was pretty straightforward actually.

**Comment by leouieda** [comment]
What do you think? If we integrate this we can make a v1.1 release and test our versioning of these datasets as well.

**Review by LL-Geo — APPROVED** [review]
👍 I like this dataset! It has a dominant anomaly in the mine area and some good structures to visualise. 😄 
I think that **altitude** should be terrain clearance as well. Its histogram matches the description on the website (80 meters).

**Comment by leouieda** [comment]
Thanks, @LL-Geo! I'm thinking if we should ship both the clearance and the topography or just calculate a height and ship just that. It would certainly save space in the CSV file.

Following from our discussions on the gravity tutorial, we may need to consider shipping topography grids with our data when the difference in resolution is large. The Bushveld one isn't that bad but if we get gravity data for this one it will be very different. So having the SRTM elevation here and as a grid later on would be unneeded duplication.

**Comment by LL-Geo** [comment]
> 

Yes, I think flight height (terrain clearance + topography) is a more common and useful term to use. It can also save data space.

I start to think about how people use their own data. In reality, they usually have separate gravity/magnetic data (including measurement heights) and a topography model. Since the horizontal resolution of SRTM is high enough (30 meters), we can do some demonstration to show how to match dem with the data resolution.  So that they can apply the same strategy to their own data.

I think it might be good to make all data has the same format (measurement height), and we can choose SRTM or Etopo depends on the model resolution. Of course, we need to make sure the filter works first... I get some time next week after I finish my AGU poster 🤣 . I can give it a go...

**Comment by leouieda** [comment]
Alright, I'll switch the two variables to `height_orthometric_m` and leave it at that. Let me know if you come up with something 🙂 

For the topography, we could actually just rely on PyGMT for that since GMT has multi-resolution topography (SRTM tiles + new compilations) with support for automatic download and caching. We plan to install PyGMT for our docs and tutorials so it wouldn't be too bad. 

Ideally, I'd love to build a light-weight Python package that just downloads these datasets. I may propose this to the devs later (maybe next summer break in July...).

**Pull request merged**
