### PR TITLE
Add GPS velocity data from the Alps

### PR DESCRIPTION
**Pull request by leouieda**
This is a compilation of 3D GPS velocities for the Alps by [Sánchez et al. (2018)](https://doi.org/10.1594/PANGAEA.886889). All velocity components and even the position have error estimates, which is very useful and rare to find in a lot of datasets. The data is less neat than the California one we used in Verde but it's good enough, has all of the uncertainties, a clear citation, and an open license. So it's a clear win for me 🙂 

index

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
See #5

**Review by santisoler — APPROVED** [review]
Looks nice! Since we already have `pygmt` in the `environment.yml`, might worth plotting the points and the quivers in an actual map. Otherwise, feel free to merge.

**Comment by leouieda** [comment]
index

How's this?

**Comment by santisoler** [comment]
Much better! Now it's easier to compare it with the figure in the paper. Feel free to merge then!

**Pull request merged**
