### PR TITLE
Add public domain singlebeam bathymetry data for the Caribbean

### PR DESCRIPTION
**Pull request by leouieda**
This dataset is a compilation of several singlebeam bathymetry surveys downloaded from the [NOAA NCEI](https://ngdc.noaa.gov/mgg/geodas/trackline.html). The data are originally in MGD77 format and include a header with metadata on each survey. The original data file has around 2 million data points and was compressed with LZMA to save space and make it possible to upload it to this GitHub repository.

index

There are some very interesting geodynamic features in this dataset and also good interpolation examples, since the islands create gaps that many interpolation methods will struggle to fill. The final compressed CSV with the data is under 8 Mb. This will be a good replacement for the bathymetry data currently used in Verde.

**License**: Public domain

**Original source**: https://ngdc.noaa.gov/mgg/geodas/trackline.html (region selected from the web interface; no direct download link)

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Review by santisoler — APPROVED** [review]
This is awesome @leouieda ! I think this is ready to be merged and then added to Rockhound.

This particular dataset opens me an idea for ditching outliers when getting block averages. We can talk about it on a meeting.

**Comment by leouieda** [comment]
Great! I'm curious to see why some lines are so different in this dataset. They seem to be off by so much that it can't be just a datum difference. Either way, I really like this dataset :-)

**Comment by Esteban82** [comment]
> This particular dataset opens me an idea for ditching outliers when getting block averages. We can talk about it on a meeting.

May I join the meeting? I also would like to ear your ideas. I have some too.

**Comment by santisoler** [comment]
> > This particular dataset opens me an idea for ditching outliers when getting block averages. We can talk about it on a meeting.
> 
> May I join the meeting? I also would like to ear your ideas. I have some too.

Sure! Fatiando Developer and Fatiando Community meetings are open to everyone, regardless of skill level.
Fatiando Developer calls takes places every Friday at 14pm GMT (11hs in Argentina). We usually post a reminder on Slack a few hours/minuets before we start. Would be great to have you onboard this week! We can talk a little bit about this idea of mine.

**Comment by Esteban82** [comment]
So tomorrow? Ok. I will try to be.

**Comment by leouieda** [comment]
It’ll be great to see you there @Esteban82!

**Comment by Esteban82** [comment]
Hi! Is it today? Now?

**Pull request merged**
