### PR TITLE
Add notebook to create bedmap2 netCDF files

### PR DESCRIPTION
**Pull request by santisoler**
Add notebook for creating netCDF files for the Bedmap2 dataset.
It creates two separate datasets: one for the ice thickness uncertainty and
another one that contains all the other grids. They are stored into separated
files because the former is defined on a different grid than the rest of the
data. Keep the original type for the arrays (mostly `int`s with few
exceptions). Don't fill `nodatavals` with `nan`s because that triggers a type
conversion to `float64`. Save the datasets as netCDF files with `zlib` encoding
to reduce disk space.

**Remember to upload the resulting files to Zenodo after merging this PR, and then update the code in Rockhound**

### CODE REVIEW

**Comment by santisoler** [comment]
@leouieda the main `.nc` file is about ~130MB, while the other one is just a few KBs. :tada:

And because `xarray` lazily opens netCDF files by default (see [`xr.load_dataset`](https://xarray.pydata.org/en/stable/generated/xarray.load_dataset.html) vs [`xr.open_dataset`](https://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html)), we don't have to split the data arrays into separated files (increasing the total size because we then would need to repeat coordinates arrays, which are `float64`): no modern laptop will crash by opening the entire `.nc` file.

**Comment by santisoler** [comment]
Try using Scipy engine for storing the netcdf.

**Comment by leouieda** [comment]
@santisoler what you like to do about this PR?

**Comment by santisoler** [comment]
> @santisoler what you like to do about this PR?

Since rockhound will be the home for the sample datasets within Fatiando, I don't see the point of adding bedmap2. In fact, I recall that there's a better dataset nowdays, so probably it doesn't worth merging this. I would then close this PR, but maybe leave the branch open in case we need the source code in the future. What do you think?

**Comment by leouieda** [comment]
Sounds good to me. I'll close this but leave the branch here then.

**Pull request closed without merging**
