### PR TITLE
Add the Britain magnetic data

### PR DESCRIPTION
**Pull request by leouieda**
Digitized survey of Britain from the British Geological Survey (Open Government License). Data quality varies and points aren't really survey data but digitized from a contour map. Still, good amount of data, coverage, and nice anomalies.

index

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Review by santisoler — APPROVED** [review]
:+1: I would just increase the padding of the colorbar on the last plot: they overlap with the tick labels.

**Comment by leouieda** [comment]
Good catch! Fixed it:

index

**Comment by leouieda** [comment]
Aaaaaand I forgot to push the commit....

**Comment by leouieda** [comment]
Pushed the missing commit to main instead.

**Pull request merged**
